name: Python CI

# Сценарій запускається при кожному push у гілку main
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Check if file exists
      run: |
        if [ -f lab_5_temp.py ]; then
          echo "Файл lab_5_temp.py знайдено!"
        else
          echo "Помилка: файл lab_5_temp.py відсутній"
          exit 1
        fi

    - name: Run script
      run: python lab_5_temp.py
